In [62]:
import numpy as np
print(np.__version__)
np.show_config()

1.15.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [157]:
z = np.zeros((10, 5), dtype='int8')

In [158]:
z.size, z.itemsize

(50, 1)

In [30]:
z = np.zeros(10);
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [33]:
z = np.arange(10, 49)
z[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [34]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
np.nonzero([2, 3, 0, 3, 0, 1])

(array([0, 1, 3, 5]),)

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
z = np.random.random((10, 10))  # `random` is an alias for the `random_sample` method
z.min(), z.max()

(0.012207483875087966, 0.9880931849149522)

In [17]:
# X = np.random.random((100, 2)) * 100
# X.astype('int')
X = np.random.randint(0, 100, (100, 2))
y = X[:, 0] + X[:, 1]
# print(X)
# print(y)
X[:, 0] * 200 

In [16]:
import numpy as np
from random import randint
from keras.layers import Dense
from keras.models import Sequential

Using TensorFlow backend.


In [ ]:
model = Sequential()
model.add(Dense(4, input_dim=2))
model.add(Dense(1))

model.compile(optimizer='SGD')

In [3]:
np.full((3, 3), np.random.randint(1, 100, (10)).max())

array([[84, 84, 84],
       [84, 84, 84],
       [84, 84, 84]])

In [123]:
np.array([np.random.randint(1, 10000000, 1000000).max() for _ in range(100)]).min()

9999949

In [142]:
a = np.arange(12).reshape((3, 4))
a[:] = np.random.randint(1, 10)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [16]:
np.repeat([[np.random.randint(1, 10), np.random.randint(10, 20)]], 5, axis=1)

array([[ 3,  3,  3,  3,  3, 18, 18, 18, 18, 18]])

In [19]:
np.tile([[1, 2], [3, 4]], (5, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [161]:
a[...] = 2
a

array([2, 2, 2, 2, 2])

In [22]:
np.fromfunction(lambda x, y: np.random.randint(1, 100, 10), (3, 3))

array([24, 71, 85, 92, 93, 40, 23, 70, 63, 77])

In [72]:
def funfun(i, j):
    if i[0][1] == j[1][0]:
        return (i, j)
    return i[0][1], j[1][1]
np.fromfunction(funfun, (3, 4), dtype=int)

(array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]]), array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]))

In [75]:
np.fromfunction(lambda i, j, k: i + j + k, (4, 2, 3))

array([[[0., 1., 2.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [2., 3., 4.]],

       [[2., 3., 4.],
        [3., 4., 5.]],

       [[3., 4., 5.],
        [4., 5., 6.]]])

In [35]:
x = np.array(
    [
        [3, 1, 1],
        [1, 7, 1],
        [7, 3, 9],
    ]
)
y = np.array(
    [
        [0, 4, 6],
        [2, 8, 0],
        [0, 4, 0],
    ]
)
cond = [
    [True, True, False],
    [True, False, False],
    [False, False, True],
]
np.where(cond, x, y * 2)
(x > 1) & (y/2 > 2)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [40]:
a = np.arange(0, 80, 10)
y = a[[1, 2, -3]]
y

array([10, 20, 50])

In [58]:
a = np.arange(25).reshape((5, -1))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
a[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 1,  7, 13, 19])

In [61]:
a[a % 3]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [77]:
a = np.arange(6, 12).reshape((2, 3))
print(a)
a.ptp(axis=1)

[[ 6  7  8]
 [ 9 10 11]]


array([2, 2])

In [74]:
help(a.ptp)

Help on built-in function ptp:

ptp(...) method of numpy.ndarray instance
    a.ptp(axis=None, out=None, keepdims=False)
    
    Peak to peak (maximum - minimum) value along a given axis.
    
    Refer to `numpy.ptp` for full documentation.
    
    See Also
    --------
    numpy.ptp : equivalent function



In [83]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  

In [84]:
a = np.arange(6).reshape((2, 3))

In [88]:
b = np.arange(-6, 0).reshape((3, 2))

In [94]:
a.dot(b) == a @ b

array([[ True,  True],
       [ True,  True]])

In [96]:
a = np.ones((3, 5))
b = np.ones((5,))


In [99]:
b.reshape((1, 5))

array([[1., 1., 1., 1., 1.]])

In [101]:
b[np.newaxis, :2]

array([[1., 1.]])

In [102]:
b[:, np.newaxis]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [120]:
x = np.array([1, 2])
y = np.array([3, 4, 5])
z = x[np.newaxis, :] + y[:, np.newaxis]

In [121]:
z

array([[4, 5],
       [5, 6],
       [6, 7]])

In [114]:
x[np.newaxis, :]

array([[1, 2]])

In [115]:
y[:, np.newaxis]

array([[3],
       [4],
       [5]])

In [117]:
x, y = np.meshgrid([1, 2], [3, 4, 5])

In [118]:
x

array([[1, 2],
       [1, 2],
       [1, 2]])

In [119]:
y

array([[3, 3],
       [4, 4],
       [5, 5]])